In [35]:
''' 
Assignment:1 
Task No. 1
1.1. Creaye a list: nums = [3, 5, 7, 8, 12], make another list named
‘cubes’ and append the cubes of the given list ‘nums’ in this list and print it.
'''
list = [3, 5, 7, 8, 12]
cubelist = []

for i in list:
    val = i*i*i
    cubelist.append(val)
    
for j in cubelist:
    print(j)

27
125
343
512
1728


In [36]:
'''
1.2 Create an empty dictionary: dict = {}, add the following data to the dictionary:
‘parrot’: 2, ‘goat’: 4, ‘spider’: 8, ‘crab’: 10 as key value pairs.'''             
dict = {}
dict.update({
    "parrot" : 2,
    "goat" : 4,
    "spider" : 8,
    "crab" : 10
})
print(dict)

{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [37]:
'''
1.3. Use the ‘items’ method to loop over the dictionary (dict) and print the animals
and their corresponding legs. Sum the legs of each animal, and print the total at the end.'''
dict = {
    "parrot" : 2,
    "goat" : 4,
    "spider" : 8,
    "crab" : 10
}

val = dict.values()
sum = 0
for i in val:
    sum = sum + i
print(sum)

24


In [38]:
#1.4. Create a tuple: A = (3, 9, 4, [5, 6]), change the value in the list from ‘5’ to ‘8’
A = (3, 9, 4, [5, 6])
A[3][0] = 8 
print(A)

(3, 9, 4, [8, 6])


In [ ]:
#1.5. Delete the tuple A
A = (3, 9, 4, [8, 6])
del A

In [39]:
#1.6.Create another tuple: B = (‘a’, ‘p’, ‘p’, ‘l’, ‘e’), print the number of occurrences of ‘p’ in the tuple.
B = ('a', 'p', 'p', 'l', 'e')
count = 0
for i in B:
    if(i == 'p'):
        count = count + 1
print(count) 

2


In [40]:
#1.7. Print the index of ‘l’ in the tuple
B = ('a', 'p', 'p', 'l', 'e')

lindex = B.index('l')
print(lindex)

3


In [24]:
#Task No.2
import numpy as np

In [25]:
#2.1 Convert matrix A into a NumPy array
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

In [26]:
#2.2 Use slicing to pull out subarray from first 2 rows and columns 1 and 2
b = A[:2, :2]
print(b)

[[1 2]
 [5 6]]


In [27]:
#2.3 Create an empty matrix C with the same shape as A
C = np.empty_like(A)
print(C)

[[      2309078893416                  64                   0
                    0]
 [  28429415029407744 7233683933424083255 3546922490233499699
  3919083175119171686]
 [4062919998563236197 3688841927835608629 7234527251007627576
  7365467192292357428]]


In [28]:
#2.4 Add vector z to each column of matrix A with a loop and store it in C
z = np.array([1, 0, 1])
for i in range(A.shape[1]):
    C[:, i] = A[:, i] + z
print(C)

[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [29]:
#2.5 Add and print the matrices X and Y
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
sum = X + Y
print(sum)

[[ 6  8]
 [10 12]]


In [30]:
#2.6 Multiply and print the matrices X and Y (element-wise multiplication)
product = X * Y
print(product)

[[ 5 12]
 [21 32]]


In [31]:
#2.7 Compute and print the element-wise square root of matrix Y
sqt = np.sqrt(Y)
print(sqt)

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [33]:
#2.8 Compute and print the dot product of the matrix X and vector v
v = np.array([9, 10])
dotproduct = np.dot(X, v)
print(dotproduct)


[29 67]


In [34]:
#2.9 Compute and print the sum of each column of X
sumcolx = np.sum(X, axis=0)
print(sumcolx)

[4 6]


In [20]:
'''
Task No.3
3.1 Create a function ‘Compute’ that takes two arguments, distance and time, and use it to calculate velocity.
'''
def Compute(inputdistance, inputtime):
    velocity = inputdistance / inputtime
    return velocity
print(Compute(100,10))


10.0


In [23]:
#3.2 Make a list named ‘even_num’ that contains all even numbers up till 12. Create a function ‘mult’ that takes the list‘even_num’ as an argument and calculates the products of all entries using a for loop.
def mult(even_num):
    productlist = 1 
    for i in even_num:
        if(i == 0):
            i = i + 1
        productlist = productlist * i
    print(f"Product Of Even Numbers In Array: {productlist}")   
    
even_num = [0, 2, 4, 6, 8, 10, 12]
mult(even_num)

Product Of Even Numbers In Array: 46080


In [ ]:
'''
Task No. 4
Create a Pandas dataframe named ‘pd’ that contains 5 rows and 4 columns,
similar to the one given below:
'''
import pandas as pd

data = {
    'C1' : [1, 2, 3, 5, 5],
    'C2' : [6, 7, 5, 4, 8],
    'C3' : [7, 9, 8, 6, 5],
    'C4' : [7, 5, 2, 8, 8],
}

In [6]:
#4.1 Print only the first two rows of the dataframe.
df = pd.DataFrame(data)
print(df)

   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [5]:
#4.2 Print the second column.
print(df['C2'])

0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [7]:
#4.3 Change the name of the third column from ‘C3’ to ‘B3’.
df.rename(columns={'C3': 'B3'}, inplace=True)
print(df)

   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [9]:
#4.4 Add a new column to the dataframe and name it ‘Sum’
df['Sum'] = df.sum(axis=1)
print(df)

   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [10]:
#4.5 Sum the entries of each row and add the result in the column ‘Sum’
df['Sum'] = df.sum(axis=1)
print(df)

   C1  C2  B3  C4  Sum
0   1   6   7   7   42
1   2   7   9   5   46
2   3   5   8   2   36
3   5   4   6   8   46
4   5   8   5   8   52


In [12]:
#4.6 Read CSV file named ‘hello_sample.csv’ (the file is available in the class Google Drive shared folder) into a Pandas dataframe.
df = pd.read_csv('hello_sample.csv')

In [13]:
#4.7 Print complete dataframe.
print(df)

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [14]:
#4.8 Print only bottom 2 records of the dataframe.
print(df.tail(2))

   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [15]:
#4.9 Print information about the dataframe.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes


In [16]:
#4.10 Print shape (rows x columns) of the dataframe.
print(df.shape)

(23, 4)


In [17]:
#4.11 Sort the data of the dataFrame using column ‘Weight’.
dfsort = df.sort_values(by='Weight')
print(dfsort)

    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
8     Male     Blue        July      60
10  Female      Red    October       60
18    Male  Mustard   December       60
6     Male   Orange      August      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [18]:
#4.12 Use isnull() and dropna() methods of the Pandas dataframe and see if they produce any changes.
missing_values = df.isnull()
print(missing_values)

    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False


In [19]:
#4.12 Use isnull() and dropna() methods of the Pandas dataframe and see if they produce any changes.
df_no_na = df.dropna()
print(df_no_na)

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66
